steedos_api_key: ${env.STEEDOS_SERVER_API_KEY}

steedos-reports-prod:
  component: "@sls-next/serverless-component@v3.6.1-alpha.2" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    domain: ["builder", "steedos.com"]
    name:
      defaultLambda: steedos-builder-prod-DefaultLambda
      apiLambda: steedos-builder-prod-ApiLambda
      imageLambda: steedos-builder-prod-ImageLambda
    stage: prod
    deploy: true
    bucketRegion: ap-east-1
    bucketName: steedos-builder-prod
    #region: ap-east-1
    runtime: nodejs14.x
    memory: 2048
    timeout: 30
    enableS3Acceleration: false
    cloudfront:
      defaults:
        viewerProtocolPolicy: 'allow-all' # optional
      # origins:
      #   - url: http://steedos-builder-prod.s3.ap-east-1.amazonaws.com
      #     pathPatterns:
      #       'static/*':
      #         viewerProtocolPolicy: 'allow-all'
      #         minTTL: 0
      #         defaultTTL: 86400
      #         maxTTL: 31536000
      #         forward: 
      #           headers: none
      #           cookies: none
      #           queryString: false
      #       '_next/static/*':
      #         viewerProtocolPolicy: 'allow-all' # optional
      #         minTTL: 0
      #         defaultTTL: 86400
      #         maxTTL: 31536000
      #         forward: 
      #           headers: none
      #           cookies: none
      #           queryString: false
    build:
      env:
        NEXT_PUBLIC_DEPLOYMENT_URL=https://builder.steedos.com
        NEXT_PUBLIC_STEEDOS_SERVER_ROOT_URL=https://console.steedos.cn
        STEEDOS_SERVER_API_KEY=${steedos_api_key}
      cleanupDotNext: true
      postBuildCommands: []

useDotenv: false
